rolex: init: Add a missing header
* Thanks to @TheTweaker for bringing this mistake to my attention
* Fixes these errors:
device/xiaomi/rolex/init/init_rolex.cpp:44:22: error: no member named 'ReadFileToString' in namespace 'android::base'
using android::base::ReadFileToString;
      ~~~~~~~~~~~~~~~^
device/xiaomi/rolex/init/init_rolex.cpp:54:9: error: use of undeclared identifier 'ReadFileToString'
    if (ReadFileToString(boot_reason_file, &boot_reason)
        ^
device/xiaomi/rolex/init/init_rolex.cpp:55:16: error: use of undeclared identifier 'ReadFileToString'
            && ReadFileToString(power_off_alarm_file, &power_off_alarm)) {
               ^